bumping versions of all python packages recommended by dependabot
open-afc-project/openafc pull request #151
Opened 2024-09-03 06:33 UTC by vitalypetrovisbest

Jinja2==3.1.4
Werkzeug==3.0.3
requests==2.32.3
certifi==2024.7.4
dnspython==2.6.1
gunicorn==23.0.0
idna==3.7

2024-09-03 14:26 UTC, mmandellrkf reviewed
With these modifications to python versions, has it been verified that none of the python functionality has been compromised?  In particular, is running daily_uls_parse.py part of the regression testing?  There are several python scripts that are invoked when running daily_uls_parse.py making this is an area where issues could potentially arise.

2024-09-03 15:27 UTC, farinazedalat commented
I agree with Mike Mandell. It'll be great if all the python scripts can be verified that are not impacted by this PR. However, since the daily_uls_parse.py is run daily, we recommend adding this to the PR's automated regression testing so that it is always verified that its functionality is not impacted.

2024-09-03 18:10 UTC, FedorSherstyukBroadcom approved these changes

2024-09-03 18:21 UTC, farinazedalat requested changes
Please see comment from myself and Mike Mandell on ensuring the existing python scripts still work (particularly the daily_uls_script) before merging.

2024-09-03 18:30 UTC, FedorSherstyukBroadcom commented
I agree that most of our Python code is not covered by tests. Not sure if we have resources to fix this.

My only hope is liveness/readiness tests that may reveal something fatal on staging phase, before production.

As for this specific change - they are related to the backend of WebUI, For this WebUI backend I recently tried to add some regression testing and failed (I mean, tests are OK, but integration attempt failed) - will discuss it with Petrov today.

2024-09-03 22:07 UTC, FedorSherstyukBroadcom commented
Probably we may sometimes make a discussion on what dependabot suggestions to accept.

2024-09-04 01:29 UTC, farinazedalat commented
Fedor, would you please that specifically the uls_daily_script.py is not impacted by this PR?

2024-09-04 11:42 UTC, vitalypetrovisbest commented
> Fedor, would you please that specifically the uls_daily_script.py is not impacted by this PR?

I will test it explicitly later today.

2024-09-04 18:09 UTC, FedorSherstyukBroadcom commented
> Fedor, would you please that specifically the uls_daily_script.py is not impacted by this PR?
Hi Farinaz,
I'm confirming that these changes do not affect ULS downloader.

2024-09-04 18:33 UTC, farinazedalat commented
> > Fedor, would you please that specifically the uls_daily_script.py is not impacted by this PR?
> > Hi Farinaz,
> > I'm confirming that these changes do not affect ULS downloader.

Hi Fedor,
Great! Thank you for confirming. Were you able to resolve testing of the backend WebUI that are impacted by this?

2024-09-05 14:38 UTC, vitalypetrovisbest commented
> Please see comment from myself and Mike Mandell on ensuring the existing python scripts still work (particularly the daily_uls_script) before merging.

I have run it manually with my changes, I've got this:

```
openafc/tests/regression>docker-compose exec uls_downloader /bin/ash
/wd # uls_downloader^C

/wd # ./uls_service.py --run_once --force
uls_service.py. WARNING: 2024-09-05 13:35:26,908 There is no point in using Prometheus in run-once mode. Use --statsd_server if metrics are necessary
uls_service.py. INFO: 2024-09-05 13:35:26,908 FS downloader started with the following parameters
uls_service.py. INFO: 2024-09-05 13:35:26,908 FS download script: /mnt/nfs/rat_transfer/daily_uls_parse/daily_uls_parse.py
uls_service.py. INFO: 2024-09-05 13:35:26,908 Additional download script parameters: None
uls_service.py. INFO: 2024-09-05 13:35:26,908 Download regions: All
uls_service.py. INFO: 2024-09-05 13:35:26,908 Directory where download script puts downloaded file: /mnt/nfs/rat_transfer/ULS_Database/
uls_service.py. INFO: 2024-09-05 13:35:26,908 Temporary directory of ULS download script, cleaned before downloading: /mnt/nfs/rat_transfer/daily_uls_parse/temp/
uls_service.py. INFO: 2024-09-05 13:35:26,909 Ultimate downloaded file destination directory: /
uls_service.py. INFO: 2024-09-05 13:35:26,909 Symlink pointing to current ULS file: rat_transfer/ULS_Database/FS_LATEST.sqlite3
uls_service.py. INFO: 2024-09-05 13:35:26,909 FSID file location expected by ULS download script: /mnt/nfs/rat_transfer/daily_uls_parse/data_files/fsid_table.csv
uls_service.py. INFO: 2024-09-05 13:35:26,909 RAS database: /rat_transfer/RAS_Database/RASdatabase.dat
uls_service.py. INFO: 2024-09-05 13:35:26,909 Where from ULS script reads RAS database: /mnt/nfs/rat_transfer/daily_uls_parse/data_files/RASdatabase.dat
uls_service.py. INFO: 2024-09-05 13:35:26,909 Connection string to service state database: postgresql://postgres:<PASSWORD>@bulk_postgres/fs_state
uls_service.py. INFO: 2024-09-05 13:35:26,909 Optional name of file with password for state database DSN: /run/secrets/ULS_STATE_DB_PASSWORD
uls_service.py. INFO: 2024-09-05 13:35:26,909 Create service state database if it is absent: Yes
uls_service.py. INFO: 2024-09-05 13:35:26,909 Recreate service state database if it exists: No
uls_service.py. INFO: 2024-09-05 13:35:26,909 Port to serve Prometheus metrics on: None
uls_service.py. INFO: 2024-09-05 13:35:26,909 StatsD server to send metrics to: None
uls_service.py. INFO: 2024-09-05 13:35:26,909 Verify that that files are the same as in internet: ['https://raw.githubusercontent.com/Wireless-Innovation-Forum/6-GHz-AFC/main/data/common_data:raw_wireless_innovation_forum_files:antenna_model_diameter_gain.csv,billboard_reflector.csv,category_b1_antennas.csv,high_performance_antennas.csv,fcc_fixed_service_channelization.csv,transmit_radio_unit_architecture.csv']
uls_service.py. INFO: 2024-09-05 13:35:26,909 Limit on number of paths changed: 10.0%
uls_service.py. INFO: 2024-09-05 13:35:26,909 AFC Service URL to use for database validity check: http://afcserver:8000/fbrat/ap-afc/availableSpectrumInquiryInternal?nocache=True
uls_service.py. INFO: 2024-09-05 13:35:26,909 Number of parallel AFC Requests to use when doing validity check: fs_afc.py's default
uls_service.py. INFO: 2024-09-05 13:35:26,909 Rcache service url: http://rcache:8000
uls_service.py. INFO: 2024-09-05 13:35:26,909 Rcache spatial invalidation: Enabled
uls_service.py. INFO: 2024-09-05 13:35:26,909 Hours to delay first download by: 1.0
uls_service.py. INFO: 2024-09-05 13:35:26,909 Download interval in hours: 4.0
uls_service.py. INFO: 2024-09-05 13:35:26,909 Download maximum duration in hours: 1.0
uls_service.py. INFO: 2024-09-05 13:35:26,909 Run in lowered (nice) priority: Yes
uls_service.py. INFO: 2024-09-05 13:35:26,909 Print debug info: No
uls_service.py. INFO: 2024-09-05 13:35:26,909 Run: Once
uls_service.py. INFO: 2024-09-05 13:35:26,909 Force FS database update (even if not changed or found invalid): Yes
uls_service.py. INFO: 2024-09-05 13:35:27,019 Running healthcheck script
uls_service_healthcheck.py. ERROR: 2024-09-05 13:35:27,275 Last download attempt happened more than 6.0 hours ago or not at all
uls_service.py. INFO: 2024-09-05 13:35:27,305 Starting ULS download
uls_service.py. INFO: 2024-09-05 13:35:27,307 Current database: 'FS_2024-08-04T03_07_00.907823_UniiUS57_fixedBPS_sorted_param.sqlite3'
uls_service.py. INFO: 2024-09-05 13:35:27,307 Extracting FSID table
uls_service.py. INFO: 2024-09-05 13:35:28,790 Copying RAS database
uls_service.py. INFO: 2024-09-05 13:35:28,814 Checking if external parameter files changed
uls_service.py. INFO: 2024-09-05 13:35:30,341 Starting nice /mnt/nfs/rat_transfer/daily_uls_parse/daily_uls_parse.py
Coalition ULS Processing Tool Version 1.3.0
Copyright 2019 (C) RKF Engineering Solutions
Thu Sep  5 13:42:31 2024 : Begin processing.
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3334 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3335 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3336 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3337 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3338 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3339 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3340 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3341 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3342 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3343 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3344 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3345 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3346 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3347 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3348 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3349 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3350 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3351 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3352 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3353 missing model name
WARNING: Transmitter Model List file "/mnt/nfs/rat_transfer/daily_uls_parse/temp/transmit_radio_unit_architecture.csv" line 3354 missing mod [...]

2024-09-05 15:34 UTC, FedorSherstyukBroadcom commented
ULS downloader log looks OK.

2024-09-05 15:37 UTC, vitalypetrovisbest commented
> ULS downloader log looks OK.

@farinazedalat can you please remove your "Change required" so I can proceed with merging?

2024-09-11 18:36 UTC, farinazedalat approved these changes

2024-09-11 21:39 UTC, merged